# Window
WINDOW_WIDTH = 600
WINDOW_HEIGHT = 400
WINDOW_LIMIT = int(WINDOW_HEIGHT/4)
WINDOW_COLOR = (0,0,20)
WINDOW_NAME = "Ping-Pong"
WINDOW_FPS = 60

# Gamezone
GAMEZONE_XCENTER = int(WINDOW_WIDTH/2)
GAMEZONE_YCENTER = (WINDOW_HEIGHT + WINDOW_LIMIT)/2 
GAMEZONE_POINTZONE = 35

# Text
TEXT_FONT = None
TEXT_SIZE = 50
TEXT_COLOR = (255, 255, 255)

# Ball
BALL_WIDTH = 10
BALL_HEIGHT = 10
BALL_COLOR = (255,255,255)
BALL_SPEED = 3
BALL_MAXSPEED = 10
BALL_INCREASESPEED = 1 / (3 * WINDOW_FPS) #3s
BALL_INCREASETIME = 10 * WINDOW_FPS #5s
BALL_INITPOSITION = (GAMEZONE_XCENTER - int(BALL_WIDTH/2), GAMEZONE_YCENTER - int(BALL_HEIGHT/2))


# Player
PLAYER_WIDTH = 10
PLAYER_HEIGHT = 60
PLAYER_COLOR = (255,255,255)
PLAYER_SPEED = 3
LPLAYER_INITPOSITION = (GAMEZONE_POINTZONE - PLAYER_WIDTH, GAMEZONE_YCENTER - int(PLAYER_HEIGHT/2))
RPLAYER_INITPOSITION = ((WINDOW_WIDTH - GAMEZONE_POINTZONE), GAMEZONE_YCENTER - int(PLAYER_HEIGHT/2))