# PALETTE
 # (37,22,5) Brown
 # (123,136,111) Green
    # (101,112,92) Dark Green
 # (246,226,167) Yellow
    #(243,219,144) Dark Yellow
 # (255,94,91) Red

# Window
WINDOW_WIDTH = 600
WINDOW_HEIGHT = 600
WINDOW_BORDER = 25
WINDOW_COLOR = (246,226,167)
WINDOW_BORDERCOLOR = (37,22,5)
WINDOW_FPS = 60
WINDOW_WAIT = 3 * 1000 # 3s

# Text
TEXT_FONT = None
TEXT_SIZE = 30
TEXT_COLOR = (255,255,255)
TEXT_FLASHING = 1 * 1000 # 1s

# Game zone
GAMEZONE_WIDTH = WINDOW_WIDTH - WINDOW_BORDER
GAMEZONE_HEIGHT = WINDOW_HEIGHT - WINDOW_BORDER

# Grid
GRID_CELLSIZE: int = 50 # 50,25; Depende del tamaño de la ventana, si son casillas muy grandes, se confunde con el borde
GRID_COLOR = (243,219,144)
GRID_NUMCELLSX = (GAMEZONE_WIDTH - WINDOW_BORDER) // GRID_CELLSIZE
GRID_NUMCELLSY = (GAMEZONE_HEIGHT - WINDOW_BORDER) // GRID_CELLSIZE

# Apple
APPLE_WIDTH = GRID_CELLSIZE
APPLE_HEIGHT = GRID_CELLSIZE
APPLE_COLOR = (255,94,91)
APPLE_INITPOSITION = (int(round(GRID_NUMCELLSX / 2, 0) + round(GRID_NUMCELLSX / 4, 0)), int(round(GRID_NUMCELLSY / 2, 0)))
APPLE_WAITGENERATE = int(0.5 * WINDOW_FPS) #0.5s

# Snake
SNAKE_WIDTH = GRID_CELLSIZE
SNAKE_HEIGHT = GRID_CELLSIZE
SNAKE_HEADCOLOR = (101,112,92)
SNAKE_COLOR = (123,136,111) 
SNAKE_WAITMOVEMENT = int(0.3 * WINDOW_FPS) #0.3s
SNAKE_DIRECTIONS = (("n", "s"), ("e", "w"))
SNAKE_HEADINITPOSITION = (int(round(GRID_NUMCELLSX / 2, 0)), int(round(GRID_NUMCELLSY / 2, 0)))
SNAKE_INITPOSITION = [SNAKE_HEADINITPOSITION, 
            (SNAKE_HEADINITPOSITION[0] -1, SNAKE_HEADINITPOSITION[1]),
            (SNAKE_HEADINITPOSITION[0] -2, SNAKE_HEADINITPOSITION[1])]
